import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/miscomponentes/Header";
import { Source_Sans_3 } from "next/font/google";

const sourceSans = Source_Sans_3({
  variable: "--font-source-sans",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});






const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${sourceSans.variable}`}>

      
      
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-white text-white p-4">
          <Header />
        </header>
        <main className="" >{children}</main>
        <footer></footer>
        
      </body>
    </html>
  );
}
